In [5]:
import numpy as np

In [6]:
arr = np.array([10,11,12,13,14])
arr

array([10, 11, 12, 13, 14])

In [8]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Create two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
# Add the two arrays
result = arr1 + arr2
print(result)

[ 7  9 11 13 15]


In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
import numpy as np

np.array([1,2,3])            # Create array
np.zeros((2,3))              # All zeros
np.ones((2,3))               # All ones
np.full((2,2),7)             # Fill with 7
np.eye(3)                    # Identity matrix
np.arange(1,10,2)            # Sequence with step
np.linspace(0,1,5)           # Evenly spaced values
np.random.rand(3)            # Random decimals
np.random.randint(1,10,5)    # Random integers
np.empty((2,2))              # Empty Array.ipynb

array([[3.5e-323, 3.5e-323],
       [3.5e-323, 3.5e-323]])

In [12]:
np.arange(1,10,2)            

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
print(arr1.size)

5


In [16]:
np.random.rand(5)


array([0.03563866, 0.44928426, 0.98036213, 0.68690108, 0.60547789])